name: jsend
description: Implementation of jsend specification in dart. 
version: 1.0.2-pre-release
repository: https://github.com/arjunQ21/jsend-dart
environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
  http: ^0.13.0

